// Generated by gencpp from file ekumen_exe1/Path_pos.msg
// DO NOT EDIT!


#ifndef EKUMEN_EXE1_MESSAGE_PATH_POS_H
#define EKUMEN_EXE1_MESSAGE_PATH_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ekumen_exe1
{
template <class ContainerAllocator>
struct Path_pos_
{
  typedef Path_pos_<ContainerAllocator> Type;

  Path_pos_()
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
    }
  Path_pos_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::ekumen_exe1::Path_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ekumen_exe1::Path_pos_<ContainerAllocator> const> ConstPtr;

}; // struct Path_pos_

typedef ::ekumen_exe1::Path_pos_<std::allocator<void> > Path_pos;

typedef boost::shared_ptr< ::ekumen_exe1::Path_pos > Path_posPtr;
typedef boost::shared_ptr< ::ekumen_exe1::Path_pos const> Path_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ekumen_exe1::Path_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ekumen_exe1::Path_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ekumen_exe1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ekumen_exe1': ['/home/rodrigo/catkin_ws/src/ekumen_exe1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ekumen_exe1::Path_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ekumen_exe1::Path_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekumen_exe1::Path_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39617ea5ffa910b78cdf07b659b77ce4";
  }

  static const char* value(const ::ekumen_exe1::Path_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39617ea5ffa910b7ULL;
  static const uint64_t static_value2 = 0x8cdf07b659b77ce4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ekumen_exe1/Path_pos";
  }

  static const char* value(const ::ekumen_exe1::Path_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 angle\n\
";
  }

  static const char* value(const ::ekumen_exe1::Path_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ekumen_exe1::Path_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ekumen_exe1::Path_pos_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EKUMEN_EXE1_MESSAGE_PATH_POS_H
