// Generated by gencpp from file ekumen_exe1/RecordingResponse.msg
// DO NOT EDIT!


#ifndef EKUMEN_EXE1_MESSAGE_RECORDINGRESPONSE_H
#define EKUMEN_EXE1_MESSAGE_RECORDINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ekumen_exe1
{
template <class ContainerAllocator>
struct RecordingResponse_
{
  typedef RecordingResponse_<ContainerAllocator> Type;

  RecordingResponse_()
    : ret(0)  {
    }
  RecordingResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
  (void)_alloc;
    }



   typedef int64_t _ret_type;
  _ret_type ret;




  typedef boost::shared_ptr< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecordingResponse_

typedef ::ekumen_exe1::RecordingResponse_<std::allocator<void> > RecordingResponse;

typedef boost::shared_ptr< ::ekumen_exe1::RecordingResponse > RecordingResponsePtr;
typedef boost::shared_ptr< ::ekumen_exe1::RecordingResponse const> RecordingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ekumen_exe1::RecordingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ekumen_exe1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ekumen_exe1': ['/home/rodrigo/catkin_ws/src/ekumen_exe1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2522e220fa06fe7901e82fcde5a0bb66";
  }

  static const char* value(const ::ekumen_exe1::RecordingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2522e220fa06fe79ULL;
  static const uint64_t static_value2 = 0x01e82fcde5a0bb66ULL;
};

template<class ContainerAllocator>
struct DataType< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ekumen_exe1/RecordingResponse";
  }

  static const char* value(const ::ekumen_exe1::RecordingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ret\n\
\n\
";
  }

  static const char* value(const ::ekumen_exe1::RecordingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecordingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ekumen_exe1::RecordingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ekumen_exe1::RecordingResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EKUMEN_EXE1_MESSAGE_RECORDINGRESPONSE_H
