// Generated by gencpp from file ekumen_exe1/RecordingRequest.msg
// DO NOT EDIT!


#ifndef EKUMEN_EXE1_MESSAGE_RECORDINGREQUEST_H
#define EKUMEN_EXE1_MESSAGE_RECORDINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ekumen_exe1
{
template <class ContainerAllocator>
struct RecordingRequest_
{
  typedef RecordingRequest_<ContainerAllocator> Type;

  RecordingRequest_()
    : command(0)  {
    }
  RecordingRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int64_t _command_type;
  _command_type command;




  typedef boost::shared_ptr< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RecordingRequest_

typedef ::ekumen_exe1::RecordingRequest_<std::allocator<void> > RecordingRequest;

typedef boost::shared_ptr< ::ekumen_exe1::RecordingRequest > RecordingRequestPtr;
typedef boost::shared_ptr< ::ekumen_exe1::RecordingRequest const> RecordingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ekumen_exe1::RecordingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ekumen_exe1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ekumen_exe1': ['/home/rodrigo/catkin_ws/src/ekumen_exe1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "856b30ed20a04e555abc88aa6a08af67";
  }

  static const char* value(const ::ekumen_exe1::RecordingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x856b30ed20a04e55ULL;
  static const uint64_t static_value2 = 0x5abc88aa6a08af67ULL;
};

template<class ContainerAllocator>
struct DataType< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ekumen_exe1/RecordingRequest";
  }

  static const char* value(const ::ekumen_exe1::RecordingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 command\n\
";
  }

  static const char* value(const ::ekumen_exe1::RecordingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecordingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ekumen_exe1::RecordingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ekumen_exe1::RecordingRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int64_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EKUMEN_EXE1_MESSAGE_RECORDINGREQUEST_H
